import type { Metadata } from 'next'
import { LegalPageShell, LegalSection } from '@/components/landing/LegalPageShell'

export const metadata: Metadata = {
  title: 'Terms of Service | RaiseSEA',
  description:
    'The terms that apply when you use RaiseSEA during the beta: what the service is, what it does not do, and what we each expect from the other.',
}

export default function TermsPage() {
  return (
    <LegalPageShell
      title="Terms of Service"
      intro="These are the terms that apply when you use RaiseSEA. They are written to be readable, and they describe what the product does and — just as importantly — what it does not do."
      updated="September 2026"
    >
      <LegalSection heading="Using RaiseSEA">
        <p>
          By creating an account or using RaiseSEA, you agree to these terms. You need to be able to enter
          into a binding agreement, and you are responsible for the activity on your account.
        </p>
      </LegalSection>

      <LegalSection heading="What RaiseSEA is">
        <p>
          RaiseSEA is a fundraising intelligence and execution platform. It helps you assess a pitch
          deck, prepare for investor meetings, identify investors whose mandate may fit your raise, run a
          fundraising pipeline, model financing structures, and follow regional market activity.
        </p>
      </LegalSection>

      <LegalSection heading="What RaiseSEA is not">
        <p>
          <strong className="font-medium text-text-primary">
            RaiseSEA does not provide investment, legal, tax or financial advice.
          </strong>{' '}
          Analysis, scores, benchmarks and matches are research aids to support your own judgement. They
          are not a recommendation to take or avoid any course of action, and they are not a valuation,
          an offer, or a solicitation.
        </p>
        <p>
          <strong className="font-medium text-text-primary">
            RaiseSEA does not introduce you to investors.
          </strong>{' '}
          We help you identify investors worth approaching and run the process well. Outreach is yours. We
          do not broker introductions, and we do not guarantee meetings, commitments or funding.
        </p>
        <p>
          Investor and market information is compiled from public sources and the regional activity we
          track. It can be incomplete or out of date. Confirm a fund&apos;s current mandate before relying
          on it.
        </p>
      </LegalSection>

      <LegalSection heading="Your content">
        <p>
          You keep ownership of the documents and information you upload. You give us what we need to
          store and process that content in order to run the product for you — nothing more.
        </p>
        <p>
          You are responsible for having the right to share anything you upload, and for the accuracy of
          what you submit.
        </p>
      </LegalSection>

      <LegalSection heading="Acceptable use">
        <p>
          Do not use RaiseSEA to break the law, to upload material you have no right to share, to probe
          or disrupt the service, to scrape or resell data, or to misrepresent analysis generated by
          RaiseSEA as independent third-party advice.
        </p>
      </LegalSection>

      <LegalSection heading="Beta service and availability">
        <p>
          RaiseSEA is offered as a beta. It is provided as-is, features may change, and interruptions may
          happen while the regional datasets deepen. Nothing here promises uninterrupted or error-free
          operation.
        </p>
      </LegalSection>

      <LegalSection heading="Price">
        <p>
          RaiseSEA is free for founders during beta. Early users will receive advance notice before any
          pricing changes take effect.
        </p>
      </LegalSection>

      <LegalSection heading="Liability">
        <p>
          To the extent permitted by law, RaiseSEA is not liable for indirect or consequential losses
          arising from your use of the product, including decisions made in reliance on analysis,
          benchmarks or investor matches.
        </p>
      </LegalSection>

      <LegalSection heading="Changes to these terms">
        <p>
          These terms will change as the product develops. Material changes will be reflected on this
          page with an updated date.
        </p>
      </LegalSection>
    </LegalPageShell>
  )
}
