import { NextRequest, NextResponse } from 'next/server'
import { getSessionUser } from '@/lib/supabase-server'
import { supabaseAdmin } from '@/lib/supabase'
import type { Debrief, DimensionScore, SlideBreakdown, QuestionBreakdown, SuggestedQuestion, PriorityFix } from '@/lib/mock-pitch'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

const esc = (s: unknown): string => {
  if (s == null) return ''
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

// GET /api/mock-pitch/debrief-pdf?sessionId=...
// Returns standalone HTML page that auto-prints. User saves as PDF from the print dialog.
export async function GET(req: NextRequest) {
  const sessionId = req.nextUrl.searchParams.get('sessionId')
  if (!sessionId) return NextResponse.json({ error: 'Missing sessionId' }, { status: 400 })

  const user = await getSessionUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: session, error } = await supabaseAdmin
    .from('mock_pitch_sessions')
    .select('*, submissions(company_name, unique_slug)')
    .eq('id', sessionId)
    .eq('user_id', user.id)
    .maybeSingle()
  if (error || !session) return NextResponse.json({ error: 'Not found' }, { status: 404 })
  if (!session.debrief) return NextResponse.json({ error: 'Debrief not yet generated' }, { status: 404 })

  const sub = (session as { submissions?: { company_name?: string; unique_slug?: string } }).submissions || {}
  const debrief = session.debrief as Debrief
  const companyName = sub.company_name || 'session'
  const date = new Date(session.started_at).toISOString().slice(0, 10)
  const safeName = companyName.replace(/[^a-zA-Z0-9_-]+/g, '_').slice(0, 40)
  const filename = `${safeName}_mock-${session.mode}_${date}`

  const html = buildHTML(filename, companyName, session.mode as 'pitch' | 'qa', session.duration_min, session.started_at, debrief)

  return new NextResponse(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `inline; filename="${filename}.html"`,
      'Cache-Control': 'no-store',
    },
  })
}

function buildHTML(filename: string, company: string, mode: 'pitch' | 'qa', durationMin: number, startedAt: string, d: Debrief): string {
  const scoreColor = colorFor(d.overall_score)
  const modeLabel = mode === 'pitch' ? `${durationMin}-min mock pitch` : `${durationMin}-min Q&A`
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${esc(filename)}</title>
<style>${STYLES}</style>
</head>
<body onload="setTimeout(() => window.print(), 500)">
<div class="page">

  <header class="hdr">
    <div>
      <div class="brand">RaiseSEA</div>
      <h1>Session debrief</h1>
      <p class="muted">${esc(company)} · ${esc(modeLabel)} · ${esc(new Date(startedAt).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' }))}</p>
    </div>
    <div class="score-box">
      <div class="score-num" style="color:${scoreColor}">${d.overall_score}<span class="score-of">/100</span></div>
      <div class="readiness ${readinessClass(d.investor_readiness)}">${esc(d.investor_readiness)}</div>
    </div>
  </header>

  <section class="summary">
    <p>${esc(d.summary)}</p>
    <div class="scoring-guide">Scoring guide: 0-44 Weak · 45-64 Needs Work · 65-79 Good · 80+ Strong</div>
  </section>

  ${Object.keys(d.dimensions || {}).length > 0 ? `
  <section>
    <h2>Dimension breakdown</h2>
    ${Object.entries(d.dimensions).map(([k, dim]) => dimensionHTML(prettyDim(k), dim)).join('')}
  </section>` : ''}

  ${mode === 'pitch' && d.per_slide?.length ? `
  <section class="page-break-before">
    <h2>Per-slide breakdown</h2>
    ${d.per_slide.map(s => slideHTML(s)).join('')}
  </section>` : ''}

  ${mode === 'qa' && d.per_question?.length ? `
  <section class="page-break-before">
    <h2>Per-question breakdown</h2>
    ${d.per_question.map((q, i) => questionHTML(q, i + 1)).join('')}
  </section>` : ''}

  ${mode === 'qa' && d.suggested_questions?.length ? `
  <section class="page-break-before">
    <h2>Other likely investor questions</h2>
    <p class="muted small">Additional questions investors are likely to ask in a real pitch — prepared talking points for each.</p>
    ${d.suggested_questions.map(sq => suggestedHTML(sq)).join('')}
  </section>` : ''}

  ${d.priority_fixes?.length ? `
  <section class="page-break-before">
    <h2>Priority fixes</h2>
    ${d.priority_fixes.map(p => priorityHTML(p)).join('')}
  </section>` : ''}

  ${d.actionable_next_steps?.length ? `
  <section class="next-steps">
    <h2>Before your next ${mode === 'pitch' ? 'pitch' : 'Q&amp;A'}</h2>
    <ol>${d.actionable_next_steps.map(s => `<li>${esc(s)}</li>`).join('')}</ol>
  </section>` : ''}

  <footer>
    <p>Generated by RaiseSEA · raisesea.co · ${new Date().toLocaleString('en-US', { dateStyle: 'medium' })}</p>
    <p class="small">Your audio was never stored — only the text transcript powered this debrief.</p>
  </footer>
</div>
</body>
</html>`
}

function dimensionHTML(name: string, dim: DimensionScore): string {
  const sc = colorFor(dim.score)
  return `<div class="card">
    <div class="card-head">
      <div>
        <div class="card-title">${esc(name)}</div>
        <div class="small muted">Weight: ${dim.weight_pct}%</div>
      </div>
      <div class="score-pill" style="background:${sc}20;color:${sc}">${dim.score} / ${dim.max_score}</div>
    </div>
    <div class="bar"><div class="bar-fill" style="width:${(dim.score / Math.max(dim.max_score, 1)) * 100}%;background:${sc}"></div></div>
    <div class="two-col">
      ${dim.found.length ? `<div><div class="lbl-ok">✓ Found</div><ul>${dim.found.map(s => `<li>${esc(s)}</li>`).join('')}</ul></div>` : '<div></div>'}
      ${dim.missing.length ? `<div><div class="lbl-bad">⚠ Missing</div><ul>${dim.missing.map(s => `<li>${esc(s)}</li>`).join('')}</ul></div>` : '<div></div>'}
    </div>
    ${dim.best_practice ? `<div class="callout callout-blue"><strong>💡 Best practice:</strong> ${esc(dim.best_practice)}</div>` : ''}
    <div class="meta small">${dim.score_impact ? `<span>${esc(dim.score_impact)}</span>` : ''}${dim.fix_effort ? `<span>Effort: <strong>${esc(dim.fix_effort)}</strong></span>` : ''}</div>
  </div>`
}

function slideHTML(s: SlideBreakdown): string {
  const sc = colorFor(s.score)
  return `<div class="card">
    <div class="card-head">
      <div class="card-title">Slide ${s.slide} <span class="pace pace-${s.pace.replace(/\s/g, '-')}">${esc(s.pace)}</span></div>
      <div class="score-pill" style="background:${sc}20;color:${sc}">${s.score} / 100</div>
    </div>
    <div class="two-col">
      ${s.what_worked.length ? `<div><div class="lbl-ok">✓ Worked</div><ul>${s.what_worked.map(x => `<li>${esc(x)}</li>`).join('')}</ul></div>` : '<div></div>'}
      ${s.what_to_improve.length ? `<div><div class="lbl-bad">⚠ Improve</div><ul>${s.what_to_improve.map(x => `<li>${esc(x)}</li>`).join('')}</ul></div>` : '<div></div>'}
    </div>
    ${s.best_practice ? `<div class="callout callout-blue"><strong>💡 How a top founder would pitch this slide:</strong> ${esc(s.best_practice)}</div>` : ''}
    ${s.how_to_be_better ? `<div class="callout callout-purple"><strong>🎯 How you can be better:</strong> ${esc(s.how_to_be_better)}</div>` : ''}
  </div>`
}

function questionHTML(q: QuestionBreakdown, idx: number): string {
  const sc = colorFor(q.score)
  return `<div class="card">
    <div class="card-head">
      <div class="small muted">Q${idx} · ${esc(q.area)}</div>
      <div class="score-pill" style="background:${sc}20;color:${sc}">${q.score} / 100</div>
    </div>
    <p class="q-text">${esc(q.q)}</p>
    <div class="two-col">
      ${q.what_worked.length ? `<div><div class="lbl-ok">✓ Worked</div><ul>${q.what_worked.map(x => `<li>${esc(x)}</li>`).join('')}</ul></div>` : '<div></div>'}
      ${q.what_was_missing.length ? `<div><div class="lbl-bad">⚠ Missing</div><ul>${q.what_was_missing.map(x => `<li>${esc(x)}</li>`).join('')}</ul></div>` : '<div></div>'}
    </div>
    ${q.best_practice_answer ? `<div class="callout callout-blue"><strong>💡 Best-practice answer:</strong> ${esc(q.best_practice_answer)}</div>` : ''}
    ${q.how_to_be_better ? `<div class="callout callout-purple"><strong>🎯 How you can be better:</strong> ${esc(q.how_to_be_better)}</div>` : ''}
    ${q.follow_ups.length ? `<div class="callout callout-amber">
      <strong>⚡ Likely follow-ups:</strong>
      ${q.follow_ups.map(f => `<div class="fu"><div class="fu-q">→ ${esc(f.q)}</div><ul class="small">${f.talking_points.map(tp => `<li>${esc(tp)}</li>`).join('')}</ul></div>`).join('')}
    </div>` : ''}
  </div>`
}

function suggestedHTML(s: SuggestedQuestion): string {
  return `<div class="card">
    <div class="small muted">${esc(s.area)}</div>
    <p class="q-text">${esc(s.q)}</p>
    ${s.talking_points.length ? `<div class="callout callout-blue"><strong>💡 Talking points:</strong><ul class="small">${s.talking_points.map(tp => `<li>${esc(tp)}</li>`).join('')}</ul></div>` : ''}
  </div>`
}

function priorityHTML(p: PriorityFix): string {
  const cls = `priority-${p.priority}`
  const label = p.priority === 'critical' ? '🔴 Critical' : p.priority === 'high' ? '🟡 High' : '🔵 Polish'
  return `<div class="card ${cls}">
    <div class="card-head">
      <div><span class="small muted">${label}</span> <strong>${esc(p.title)}</strong></div>
      <div class="small">${p.score_impact ? esc(p.score_impact) + ' · ' : ''}Effort: <strong>${esc(p.effort)}</strong></div>
    </div>
    <p class="small">${esc(p.description)}</p>
  </div>`
}

function colorFor(score: number): string {
  if (score >= 80) return '#059669'
  if (score >= 65) return '#d97706'
  if (score >= 45) return '#ea580c'
  return '#dc2626'
}
function readinessClass(r: string): string { return `r-${r.toLowerCase().replace(/\s+/g, '-')}` }
function prettyDim(k: string): string { return k.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') }

const STYLES = `
* { box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 11pt; color: #111; line-height: 1.5; margin: 0; padding: 0; background: #fff; }
.page { max-width: 800px; margin: 0 auto; padding: 32px 24px; }
.hdr { display: flex; justify-content: space-between; align-items: flex-start; gap: 16px; padding-bottom: 16px; border-bottom: 2px solid #1a4d2e; }
.brand { font-size: 9pt; letter-spacing: 0.15em; color: #1a4d2e; font-weight: 700; text-transform: uppercase; }
h1 { font-size: 24pt; margin: 4px 0 0 0; color: #111; font-weight: 600; }
h2 { font-size: 14pt; color: #1a4d2e; margin: 24px 0 12px 0; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
.muted { color: #6b7280; }
.small { font-size: 9pt; }
.score-box { text-align: right; }
.score-num { font-size: 42pt; font-weight: 700; line-height: 1; }
.score-of { font-size: 18pt; opacity: 0.6; }
.readiness { display: inline-block; padding: 4px 10px; border-radius: 999px; font-size: 10pt; font-weight: 600; margin-top: 4px; }
.r-strong { background: #d1fae5; color: #065f46; }
.r-good { background: #fef3c7; color: #92400e; }
.r-needs-work { background: #fed7aa; color: #9a3412; }
.r-weak { background: #fee2e2; color: #991b1b; }
.summary { background: #f9fafb; border-left: 3px solid #1a4d2e; padding: 12px 16px; margin: 16px 0; }
.scoring-guide { margin-top: 8px; font-size: 9pt; color: #6b7280; }
section { margin-bottom: 20px; }
.card { background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 14px; margin-bottom: 10px; }
.card-head { display: flex; justify-content: space-between; align-items: flex-start; gap: 8px; margin-bottom: 8px; }
.card-title { font-weight: 600; font-size: 11pt; color: #111; }
.score-pill { padding: 2px 8px; border-radius: 999px; font-weight: 600; font-size: 9pt; }
.bar { width: 100%; height: 4px; background: #f3f4f6; border-radius: 2px; overflow: hidden; margin: 6px 0 10px 0; }
.bar-fill { height: 100%; }
.two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 8px 0; }
.lbl-ok { font-size: 9pt; color: #065f46; font-weight: 600; text-transform: uppercase; margin-bottom: 4px; }
.lbl-bad { font-size: 9pt; color: #991b1b; font-weight: 600; text-transform: uppercase; margin-bottom: 4px; }
ul { margin: 0; padding-left: 16px; }
li { margin: 2px 0; font-size: 10pt; }
.callout { padding: 8px 10px; border-radius: 6px; margin-top: 8px; font-size: 10pt; }
.callout-blue { background: #eff6ff; border: 1px solid #dbeafe; color: #1e3a8a; }
.callout-purple { background: #faf5ff; border: 1px solid #f3e8ff; color: #581c87; }
.callout-amber { background: #fffbeb; border: 1px solid #fef3c7; color: #92400e; }
.fu { margin-top: 6px; }
.fu-q { font-weight: 600; font-size: 10pt; }
.pace { font-size: 8pt; padding: 1px 6px; border-radius: 999px; font-weight: 600; text-transform: uppercase; margin-left: 6px; }
.pace-silent { background: #f3f4f6; color: #6b7280; }
.pace-good { background: #d1fae5; color: #065f46; }
.pace-too-fast, .pace-too-slow { background: #fef3c7; color: #92400e; }
.q-text { font-size: 11pt; font-weight: 500; color: #111; margin: 4px 0 10px 0; }
.meta { display: flex; gap: 12px; justify-content: space-between; margin-top: 6px; color: #6b7280; }
.priority-critical { border-left: 3px solid #dc2626; background: #fef2f2; }
.priority-high { border-left: 3px solid #d97706; background: #fffbeb; }
.priority-polish { border-left: 3px solid #6b7280; background: #f9fafb; }
.next-steps { background: #eff6ff; border: 1px solid #dbeafe; border-radius: 8px; padding: 14px 16px; }
.next-steps ol { margin: 6px 0 0 0; padding-left: 18px; }
.next-steps li { margin: 4px 0; font-size: 10pt; }
footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 9pt; color: #6b7280; text-align: center; }
@media print {
  .page { padding: 16px; max-width: 100%; }
  .page-break-before { page-break-before: always; }
  body { background: white !important; }
  .card { break-inside: avoid; }
}
`
